services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB_NAME}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '${POSTGRES_PORT}:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '${REDIS_PORT}:6379'
